services:
  anyconnect-proxy:
    build:
      context: .
    container_name: anyconnect-proxy
    env_file: .env
    ports:
      - "${LOCAL_PROXY_PORT:-9052}:9052"
    restart: unless-stopped
    cpus: 0.5
    mem_limit: 128m
    volumes:
      - cisco:/root/.cisco

volumes:
  cisco:
    name: cisco
